name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      - name: Install wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb

      - name: Install Odoo dependencies
        run: |
          pip install wheel
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdfminer.six   # Add this line to install pdfminer.six

      - name: Run tests
        run: |
          ./odoo-bin -c /etc/odoo17.conf --stop-after-init --test-enable --log-level=test
          

      - name: Add SSH key and known hosts
        if: github.ref == 'refs/heads/main'
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: 172.105.174.68
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

           - name: Deploy to Production
            run: |
          ssh root@172.105.174.68 'bash -s' << 'EOF'
          cd /opt/odoo17
          git pull origin main
          ./odoo-bin -c /etc/odoo17.conf
          EOF
