name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libldap2-dev libsasl2-dev libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdfminer.six   # Add this line to install pdfminer.six

      - name: Run tests
        run: |
          # Add your test commands here
          # echo "Running tests"
          odoo-bin --addons-path=addons -d test_db --stop-after-init --test-enable

      - name: Add SSH key and known hosts
        if: github.ref == 'refs/heads/main'
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: 172.105.174.68
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

           - name: Deploy to Production
            run: |
          ssh root@172.105.174.68 'bash -s' << 'EOF'
          cd /opt/odoo17
          git pull origin main
          ./odoo-bin -c /etc/odoo17.conf
          EOF
